window.LEVEL_FOUR_WORDS = [
  ['about','關於'],['above','在…之上'],['a lot (of)','許多'],['again','再一次'],['ago','…以前'],['airport','機場'],['always','總是'],['animal','動物'],['as','好像；當作'],
  ['bacon','培根'],['bank','銀行'],['barbecue (BBQ)','烤肉'],['beach','海灘'],['because','因為'],['bell','鈴；鐘'],['bookstore','書店'],['boring','無趣的'],['bread','麵包'],['breakfast','早餐'],['bring','帶來'],['build','建造'],['building','建築物'],['bulletin board','布告欄'],['busy','忙碌的'],['but','但是'],['butter','奶油'],['by','藉由…'],
  ['calendar','日曆'],['can','罐（頭）'],['cap','鴨舌帽'],['carrier','快遞員；宅配員'],['carry','攜帶'],['city','城市'],['clean','清潔；乾淨的'],['close','接近的；親密的'],['correct','正確的'],['country','國家；鄉下'],['crazy','瘋狂的'],['crocodile','鱷魚'],['cut','剪；切'],['cute','可愛的'],
  ['dark','暗的；深色的'],['dinner','晚餐'],['dirty','骯髒的'],['dry','乾的'],['dryer','吹風機'],['email','電子郵件'],['English','英文'],
  ['fast','快的'],['find','發現'],['fire station','消防局'],['flower shop','花店'],['for','給…；為了…'],['forest','森林'],['fruit','水果'],['fun','樂趣；有趣的'],['funny','有趣的；奇怪的'],
  ['garden','花園'],['giraffe','長頸鹿'],['gorilla','大猩猩'],['ground','地面'],['hear','聽'],['help','幫忙'],['hers','她的'],['high','高的'],['hippo (hippopotamus)','河馬'],['his','他的'],['honey','蜂蜜'],['idea','點子；想法'],['interesting','有趣的'],['its','它的；牠的'],['jam','果醬'],['jar','罐'],['ketchup','番茄醬'],['kitten','小貓'],
  ['lake','湖'],['large','大的'],['last (night / week)','上一個；最後的'],['leave','離開'],['letter','信；字母'],['look for','尋找…'],['low','低的'],['lunch','午餐'],
  ['magic','魔法'],['magician','魔術師'],['mail','信件；郵寄'],['mail carrier','郵差'],['math','數學'],['meal','餐'],['meat','肉'],['mind','介意；心智'],['mine','我的'],['mountain','山'],['musician','音樂家'],['near','在…附近'],['never','從未'],['note (s)','筆記；短箋'],['notebook','筆記本；手提電腦'],
  ['off','關閉；遠離'],['often','經常'],['once','一次'],['only','唯一的；只'],['ours','我們的'],['oven','烤箱'],
  ['park','公園；停車'],['pay','付錢'],['pepper','胡椒粉'],['pick','挑選；採摘'],['pick up','撿起；以車接（人）'],['player','演奏者；球員'],['playground','遊樂場；操場'],['police station','警察局'],['pork','豬肉'],['postcard','明信片'],['post office','郵局'],['puppy','小狗'],['rarely','很少；難得'],['river','河'],
  ['salt','鹽'],['sausage','香腸'],['say','說'],['science','科學'],['scientist','科學家'],['sea','海'],['seat','座位'],['seesaw','翹翹板'],['seldom','不常；很少'],['send','寄；發送'],['shop','商店；購物'],['slide','滑梯'],['slow','慢的'],['smile','微笑'],['snack','點心'],['snowman','雪人'],['sometimes','有時候'],['station','局；所；站'],['stay','停留'],['street','街道'],['strong','強壯的'],['student','學生'],['study','學習；研讀'],['sugar','糖'],['supermarket','超級市場'],['sweet','甜的'],['swing','鞦韆'],
  ['take off','脫掉'],['teach','教'],['television','電視'],['tell','說；告訴'],['test','考試'],['than','比；比較'],['theirs','他們的'],['thirsty','口渴的'],['thousand','（一）千'],['tonight','今晚'],['town','城鎮'],['train station','火車站'],['turn','轉動；翻；輪流'],['turn off','關掉'],['turn on','打開'],['twice','兩次'],['usually','通常'],['vegetable','蔬菜'],['village','村莊'],['visit','拜訪；參觀'],['wait','等待'],['weak','虛弱的'],['week','星期'],['weekend','週末'],['wet','濕的'],['which','哪個'],['whose','誰的'],['why','為什麼'],['wonderful','令人驚奇的；極好的'],['world','世界'],['would','將要'],['wrong','錯誤的'],['yard','院子'],['year','年'],['yesterday','昨天'],['yours','你的；你們的']
].map(([word, meaning], index) => ({ id: index + 1, word, meaning }));
